name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Actualizado a Node 20 para que Vite 7 no falle

      - name: Instalar dependencias y compilar
        run: |
          npm install
          npm run build

      - name: Configurar la clave privada SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 44.193.254.173 >> ~/.ssh/known_hosts

      - name: Desplegar archivos con rsync
        run: |
          # Tu comando original con el truco para que no falle por los permisos de Linux
          rsync -avz --delete --no-perms --no-owner --no-group ./ ubuntu@44.193.254.173:/var/www/frontend/
